version: '3.8'

services:
  api:
    build: .
    container_name: mlflow-api
    command: sh -c "uvicorn mlFlow_api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  streamlit:
    build: .
    container_name: mlflow-streamlit 
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root /app/mlartifacts
    volumes:
      - ./mlartifacts:/app/mlartifacts
      - ./mlruns:/mlflow/mlruns
