name: CI

on:
  push:
    branches: [ main, dev ]  # Branch to survey
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    # defaults:
    #   run:
    #     working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r <(pip freeze > requirements.txt && cat requirements.txt)
          # Add any specific installation commands for libcpab
          # pip install -e libcpab


      - name: Run unit tests
        run: |
          pytest tests/test_calcul.py
